PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE sessions (id integer primary key, session_key text unique, name text, DateStart integer, DateEnd integer, title text, comments text, expiry integer);
INSERT INTO "sessions" VALUES(1,'123456','admin','','','Администратор','Административная сессия','0');
CREATE TABLE experiments (id integer primary key, session_key text, title text, setup_id integer, DateStart_exp integer, DateEnd_exp integer, comments integer, FOREIGN KEY(session_key) REFERENCES sessions(session_key));
CREATE TABLE setups(id integer primary key, master_exp_id integer, title text, interval integer, amount integer DEFAULT NULL, time_det integer DEFAULT NULL, period integer DEFAULT NULL, number_error integer DEFAULT NULL, period_repeated_det integer DEFAULT NULL, flag integer, FOREIGN KEY(master_exp_id) REFERENCES experiments(id) );
CREATE TABLE setup_conf (id integer primary key, setup_id integer, sensor_id text, sensor_val_id integer, name text, FOREIGN KEY(setup_id) REFERENCES setups(id));
CREATE TABLE consumers (id integer primary key, setup_id integer, exp_id integer, FOREIGN KEY(exp_id) REFERENCES experiments(id), FOREIGN KEY(setup_id) REFERENCES setups(id));
CREATE TABLE sensors (id integer primary key, sensor_id text, sensor_val_id integer, sensor_name text, value_name text, si_notation text, si_name text,  max_range integer DEFAULT NULL, min_range integer DEFAULT NULL, error real, resolution bigint DEFAULT NULL);
CREATE TABLE detections (id integer primary key, exp_id integer, time text, sensor_id text, sensor_val_id integer, detection real, error text DEFAULT NULL, FOREIGN KEY(exp_id) REFERENCES experiments(id), FOREIGN KEY(sensor_id) REFERENCES sensors(sensor_id));
CREATE TABLE plots (id integer primary key, exp_id integer, id_sensor_x integer, sensor_val_id_x integer, scales real, start text, stop text, foreign key (exp_id) references experiments(id), foreign key (id_sensor_x) references sensors(id));
CREATE TABLE ordinate (id integer primary key, id_plot integer, id_sensor_y integer, sensor_val_id_y integer, scales real, start text, stop text, foreign key(id_plot) references plots(id), foreign key (id_sensor_y) references sensors(id));
CREATE TABLE monitors (id integer primary key, exp_id integer, setup_id integer, uuid text, created text, deleted integer, FOREIGN KEY (exp_id) REFERENCES experiments(id), FOREIGN KEY (setup_id) REFERENCES setups (id) );
COMMIT;
